export const data1 = [
  "Acura",
  "Alfa Romeo",
  "Aston Martin",
  "Audi",
  "Bentley",
  "BMW",
  "Buick",
  "Cadillac",
  "Chevrolet",
  "Chrysler",
  "Citroen",
  "Dodge",
  "Ferrari",
  "Fiat",
  "Ford",
  "GMC",
  "Honda",
  "Hyundai",
  "Infiniti",
  "Jaguar",
  "Jeep",
  "Kia",
  "Lamborghini",
  "Land Rover",
  "Lexus",
  "Lincoln",
  "Maserati",
  "Mazda",
  "McLaren",
  "Mercedes-Benz",
  "MINI",
  "Mitsubishi",
  "Nissan",
  "Porsche",
  "Ram",
  "Rolls-Royce",
  "Subaru",
  "Tesla",
  "Toyota",
  "Volkswagen",
  "Volvo",
  "Datsun",
  "Subaru",
  "Peugeot",
  "Renault",
  "Skoda",
  "Tata",
  "Proton",
  "Chery",
  "Geely",
  "BYD",
  "Great Wall",
  "Mitsubishi Fuso",
  "Daewoo",
  "SsangYong",
  "MG",
  "Roewe",
  "Haval",
  "Wuling",
  "Changhe",
  "Brilliance",
  "Foton",
  "Haima",
  "JAC",
  "Lifan",
  "NIO",
  "Xpeng",
  "Lucid",
  "Rivian",
  "Rimac",
  "Polestar",
  "Nikola",
  "Rivian",
  "Fisker",
  "Rivian",
  "Bollinger",
  "Lordstown",
  "Canoo",
  "Karma",
  "Rivian",
  "Faraday Future",
  "Lucid",
  "Rivian",
  "Nikola",
  "Rivian",
  "Nikola",
  "Rivian",
  "Bollinger",
  "Toyota",
  "Honda",
  "Ford",
  "Chevrolet",
  "Nissan",
  "Volkswagen",
  "BMW",
  "Mercedes-Benz",
  "Audi",
  "Hyundai",
  "Kia",
  "Mazda",
  "Subaru",
  "Jeep",
  "Lexus",
  "Acura",
  "Porsche",
  "Tesla",
  "Ferrari",
  "Maserati",
  "Jaguar",
  "Lamborghini",
  "Chrysler",
  "Dodge",
  "Volvo",
  "Land Rover",
  "Buick",
  "Cadillac",
  "GMC",
  "Mini",
  "Mitsubishi",
  "Suzuki",
  "Aston Martin",
  "Bentley",
  "Rolls-Royce",
  "Alfa Romeo",
  "Fiat",
  "Lincoln",
  "Infiniti",
  "Koenigsegg",
  "McLaren",
  "Bugatti",
  "Pagani",
  "Lotus",
  "Morgan",
  "Spyker",
  "Saleen",
  "Karma",
];
function uniqueFilter(value: string, index: number, self: string[]): boolean {
  return self.indexOf(value) === index;
}
export const manufacturerBrands: string[] = data1.filter(uniqueFilter);

export const yearsOfProduction = [
  { title: "Year", value: "" },
  { title: "2015", value: "2015" },
  { title: "2016", value: "2016" },
  { title: "2017", value: "2017" },
  { title: "2018", value: "2018" },
  { title: "2019", value: "2019" },
  { title: "2020", value: "2020" },
  { title: "2021", value: "2021" },
  { title: "2022", value: "2022" },
  { title: "2023", value: "2023" },
];

export const fuels = [
  {
    title: "Fuel",
    value: "",
  },
  {
    title: "Gas",
    value: "Gas",
  },
  {
    title: "Electricity",
    value: "Electricity",
  },
];

export const footerLinks = [
  {
    title: "About",
    links: [
      { title: "How it works", url: "/" },
      { title: "Featured", url: "/" },
      { title: "Partnership", url: "/" },
      { title: "Bussiness Relation", url: "/" },
    ],
  },
  {
    title: "Company",
    links: [
      { title: "Events", url: "/" },
      { title: "Blog", url: "/" },
      { title: "Podcast", url: "/" },
      { title: "Invite a friend", url: "/" },
    ],
  },
  {
    title: "Socials",
    links: [
      { title: "Discord", url: "/" },
      { title: "Instagram", url: "/" },
      { title: "Twitter", url: "/" },
      { title: "Facebook", url: "/" },
    ],
  },
];
